### ISSUE TITLE
authpass.py文件中key1和key2语法错误

### ISSUE THREAD

**Issue by neilxu6** [yingchi/coursera-downloader#1]
SyntaxError: Non-ASCII character '\xe1' in file coursera-downloader/authpass.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by yingchi** [comment]
Hi, thanks for you feedback. It seems that your system cannot interpret those latin characters. They are just random keys to encode your account information. Just change them to any strings you like, remember to make sure the string length is multiple of 16 bytes. A simple example can be '1234567812345678'.
